#!/usr/bin/env python3
"""generate-reference-pages.py — emit per-agent, per-command, per-skill
reference docs under `sdf/docs/reference/{agents,commands,skills}/`.

Idempotent. Reads frontmatter from source files; emits a standard stub.
Running this script should produce a clean diff only when sources changed.

Design choices
--------------
- Keep emitted files SHORT. Each is a stub pointing to the real source
  (agent .md / skill SKILL.md / command .md). The stub is the SEO-style
  single-line-per-field reference, not a re-hosting of content.
- Mark emitted files with a banner: "Auto-generated by generate-reference-pages.py".
- Ship a `.manifest` header comment capturing source path + hash so drift
  is detectable.
- Every emitted file cites the canonical ADRs.

Usage
-----
  python sdf/scripts/ecosystem/generate-reference-pages.py
  python sdf/scripts/ecosystem/generate-reference-pages.py --check   # CI mode

Exit codes:
  0 — succeeded (or --check found no drift)
  1 — drift detected in --check mode (regenerated but would need commit)

Antifragile property
--------------------
Run in CI on every push touching agents/commands/skills. Drift → failing
build → forces contributor to commit regenerated pages. Source of truth
stays the frontmatter; the reference pages are a projection.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
SDF = REPO_ROOT / "sdf"

AGENTS_SRC = SDF / "agents"
SKILLS_SRC = SDF / "skills"
COMMANDS_SRC = SDF / "commands"

REFDIR = SDF / "docs" / "reference"
AGENTS_OUT = REFDIR / "agents"
SKILLS_OUT = REFDIR / "skills"
COMMANDS_OUT = REFDIR / "commands"

BANNER = "<!-- Auto-generated by scripts/ecosystem/generate-reference-pages.py — do not edit by hand -->"

FM_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.S)


@dataclass
class Frontmatter:
    fields: dict[str, str]
    body_preview: str  # first ~200 chars of body, stripped

    @classmethod
    def parse(cls, path: Path) -> "Frontmatter":
        text = path.read_text(encoding="utf-8", errors="replace")
        m = FM_RE.match(text)
        fields: dict[str, str] = {}
        body = text
        if m:
            raw = m.group(1)
            body = text[m.end():]
            for line in raw.splitlines():
                line = line.rstrip()
                if ":" not in line or line.startswith((" ", "-")):
                    continue
                k, _, v = line.partition(":")
                fields[k.strip()] = v.strip().strip('"')
        # Preview: strip ATX headings' # and take first meaningful paragraph
        preview = ""
        for para in body.split("\n\n"):
            p = para.strip()
            if p and not p.startswith(("#", "<!--", "---")):
                preview = p.replace("\n", " ")[:240]
                break
        return cls(fields=fields, body_preview=preview)


def slug_from_path(p: Path, src: Path) -> str:
    rel = p.relative_to(src)
    # For skills: <slug>/SKILL.md → <slug>
    if rel.name == "SKILL.md":
        return rel.parent.name
    return rel.stem


def file_hash(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()[:12]


def emit_agent_page(path: Path) -> str:
    fm = Frontmatter.parse(path)
    slug = path.stem
    name = fm.fields.get("name", slug)
    desc = fm.fields.get("description", "")
    tools = fm.fields.get("tools", "")
    model = fm.fields.get("model", "inherit")
    src_rel = path.relative_to(REPO_ROOT).as_posix()
    h = file_hash(path)
    return f"""{BANNER}
<!-- source: {src_rel} · sha256: {h} -->

# Agent · `{name}`

- **Source**: [`../../../agents/{slug}.md`](../../../agents/{slug}.md)
- **Tools**: `{tools or '(default)'}`
- **Model**: `{model}`

## Description

{desc or '(no description in frontmatter)'}

## Summary

{fm.body_preview or '(no body preview available)'}

## Related

- Committee composition: [`references/ontology/agent-committee.md`](../../../references/ontology/agent-committee.md)
- Agent architecture: [ADR-0001](../../adr/0001-agent-committee-composition.md)
"""


def emit_command_page(path: Path) -> str:
    fm = Frontmatter.parse(path)
    slug = path.stem
    name = fm.fields.get("name", slug)
    desc = fm.fields.get("description", "")
    hint = fm.fields.get("argument-hint", "")
    src_rel = path.relative_to(REPO_ROOT).as_posix()
    h = file_hash(path)
    return f"""{BANNER}
<!-- source: {src_rel} · sha256: {h} -->

# Command · `/sdf:{name}`

- **Source**: [`../../../commands/{slug}.md`](../../../commands/{slug}.md)
- **Argument hint**: `{hint or '(none)'}`

## Description

{desc or '(no description in frontmatter)'}

## Usage snippet (body preview)

{fm.body_preview or '(no body preview available)'}

## Related

- Command catalogue: [`references/ontology/commands-reference.md`](../../../references/ontology/commands-reference.md)
"""


def emit_skill_page(path: Path) -> str:
    fm = Frontmatter.parse(path)
    slug = path.parent.name
    name = fm.fields.get("name", slug)
    desc = fm.fields.get("description", "")
    tools = fm.fields.get("allowed-tools", "")
    author = fm.fields.get("author", "(unspecified)")
    src_rel = path.relative_to(REPO_ROOT).as_posix()
    h = file_hash(path)
    # 7/7 check: count companion assets
    skill_dir = path.parent
    present = {
        "SKILL.md": path.exists(),
        "agents/grader.md": (skill_dir / "agents" / "grader.md").exists(),
        "evals/evals.json": (skill_dir / "evals" / "evals.json").exists(),
        "references/": (skill_dir / "references").is_dir(),
        "examples/": (skill_dir / "examples").is_dir(),
        "scripts/": (skill_dir / "scripts").is_dir(),
        "prompts/": (skill_dir / "prompts").is_dir(),
    }
    score = sum(1 for v in present.values() if v)
    checklist = "\n".join(f"- [{'x' if v else ' '}] {k}" for k, v in present.items())
    return f"""{BANNER}
<!-- source: {src_rel} · sha256: {h} -->

# Skill · `{name}`

- **Source**: [`../../../skills/{slug}/SKILL.md`](../../../skills/{slug}/SKILL.md)
- **Allowed tools**: `{tools or '(default)'}`
- **Author**: {author}
- **INSIGNIA score**: **{score}/7**

## Description

{desc or '(no description in frontmatter)'}

## Summary

{fm.body_preview or '(no body preview available)'}

## 7/7 INSIGNIA contract

{checklist}

## Related

- [ADR-0005](../../adr/0005-insignia-7of7-structure.md) — why 7/7
- [`references/ontology/skills-catalog.md`](../../../references/ontology/skills-catalog.md)
"""


def collect_sources() -> tuple[list[Path], list[Path], list[Path]]:
    agents = sorted(
        p for p in AGENTS_SRC.glob("*.md")
        if p.name not in ("README.md",)
    )
    commands = sorted(
        p for p in COMMANDS_SRC.glob("*.md")
        if p.name not in ("README.md",)
    )
    skills = sorted(SKILLS_SRC.glob("*/SKILL.md"))
    return agents, commands, skills


def write_if_changed(dst: Path, content: str) -> bool:
    """Returns True if file was written (content differs)."""
    if dst.is_file() and dst.read_text(encoding="utf-8") == content:
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(content, encoding="utf-8")
    return True


def emit_index(kind: str, entries: list[tuple[str, str]]) -> str:
    """entries is [(slug, short_desc), ...]"""
    lines = [
        BANNER, "", f"# {kind.title()} — auto-generated reference index", "",
        f"**{len(entries)} {kind}** in SDF. Each entry is a generated stub pointing to the canonical source.", "",
        "| Slug | Description |", "|------|-------------|",
    ]
    for slug, desc in entries:
        short = desc.replace("|", "\\|")[:120]
        lines.append(f"| [`{slug}`]({slug}.md) | {short} |")
    lines.append("")
    lines.append("Regenerate: `python sdf/scripts/ecosystem/generate-reference-pages.py`")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if drift detected")
    args = parser.parse_args()

    agents, commands, skills = collect_sources()
    drift = False
    counts = {"agents": 0, "commands": 0, "skills": 0}

    # Agents
    agent_entries: list[tuple[str, str]] = []
    for p in agents:
        fm = Frontmatter.parse(p)
        slug = p.stem
        desc = fm.fields.get("description", "")
        dst = AGENTS_OUT / f"{slug}.md"
        if write_if_changed(dst, emit_agent_page(p)):
            counts["agents"] += 1
            drift = True
        agent_entries.append((slug, desc))
    if write_if_changed(AGENTS_OUT / "README.md", emit_index("agents", agent_entries)):
        drift = True

    # Commands
    command_entries: list[tuple[str, str]] = []
    for p in commands:
        fm = Frontmatter.parse(p)
        slug = p.stem
        desc = fm.fields.get("description", "")
        dst = COMMANDS_OUT / f"{slug}.md"
        if write_if_changed(dst, emit_command_page(p)):
            counts["commands"] += 1
            drift = True
        command_entries.append((slug, desc))
    if write_if_changed(COMMANDS_OUT / "README.md", emit_index("commands", command_entries)):
        drift = True

    # Skills
    skill_entries: list[tuple[str, str]] = []
    for p in skills:
        fm = Frontmatter.parse(p)
        slug = p.parent.name
        desc = fm.fields.get("description", "")
        dst = SKILLS_OUT / f"{slug}.md"
        if write_if_changed(dst, emit_skill_page(p)):
            counts["skills"] += 1
            drift = True
        skill_entries.append((slug, desc))
    if write_if_changed(SKILLS_OUT / "README.md", emit_index("skills", skill_entries)):
        drift = True

    total = len(agents) + len(commands) + len(skills)
    print(f"[generate-reference-pages] agents={len(agents)} commands={len(commands)} skills={len(skills)} total={total}")
    print(f"[generate-reference-pages] written: agents={counts['agents']} commands={counts['commands']} skills={counts['skills']}")

    if args.check and drift:
        print("[generate-reference-pages] DRIFT: regenerate and commit.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
