#!/usr/bin/env bash
# pm-init.sh — Interactive initialization wizard for PMO-APEX
# PMO-APEX v1.0 — Agentic Project Management as Service
# © 2026 PMO-APEX. All Rights Reserved.
#
# Sets up project/ structure, pre-populates session context,
# runs G0 security scan, and prepares the environment for Claude Code.

set -euo pipefail

PLUGIN_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TARGET_DIR="${1:-$(pwd)}"

# ─── Banner ───
cat << 'BANNER'

  ================================================================
  |                                                              |
  |   PMO-APEX v1.0                                              |
  |   Agentic Project Management as Service                     |
  |                                                              |
  |   Interactive Initialization Wizard                          |
  |   (c) 2026 PMO-APEX                                         |
  |                                                              |
  ================================================================

BANNER

echo "Target directory: $TARGET_DIR"
echo ""

# ─── Step 1: Interactive questions ───
echo "--- Step 1/6: Project Information ---"
echo ""

read -rp "  Project name: " PROJECT_NAME
PROJECT_NAME="${PROJECT_NAME:-ProjectDemo}"

echo ""
echo "  Project types available:"
echo "    1) Agile — Scrum/XP iterative delivery"
echo "    2) Kanban — Flow-based continuous delivery"
echo "    3) SAFe — Scaled Agile Framework"
echo "    4) Waterfall — Sequential phase-gate"
echo "    5) Hybrid — Mixed Agile + Waterfall"
echo "    6) PMO — PMO setup and governance"
echo "    7) Portfolio — Multi-project portfolio management"
echo "    8) Transformation — Organizational transformation"
echo "    9) Recovery — Troubled project recovery"
echo ""
read -rp "  Select project type [1-9, default 1]: " TIPO_NUM
case "${TIPO_NUM:-1}" in
  1) TIPO_PROYECTO="Agile" ;;
  2) TIPO_PROYECTO="Kanban" ;;
  3) TIPO_PROYECTO="SAFe" ;;
  4) TIPO_PROYECTO="Waterfall" ;;
  5) TIPO_PROYECTO="Hybrid" ;;
  6) TIPO_PROYECTO="PMO" ;;
  7) TIPO_PROYECTO="Portfolio" ;;
  8) TIPO_PROYECTO="Transformation" ;;
  9) TIPO_PROYECTO="Recovery" ;;
  *) TIPO_PROYECTO="Agile" ;;
esac

echo ""
echo "  Pipeline modes available:"
echo "    1) run-auto — Full autonomous pipeline"
echo "    2) run-express — Quick Go/No-Go (3 deliverables)"
echo "    3) run-guided — Guided pipeline with human facilitation"
echo "    4) run-deep — Deep analysis (7 deliverables, 2 gates)"
echo ""
read -rp "  Select pipeline mode [1-4, default 1]: " MODE_NUM
case "${MODE_NUM:-1}" in
  1) PIPELINE_MODE="run-auto" ;;
  2) PIPELINE_MODE="run-express" ;;
  3) PIPELINE_MODE="run-guided" ;;
  4) PIPELINE_MODE="run-deep" ;;
  *) PIPELINE_MODE="run-auto" ;;
esac

echo ""
read -rp "  Repository path (optional, Enter to skip): " REPO_PATH
REPO_PATH="${REPO_PATH:-N/A}"

echo ""
read -rp "  Key stakeholders (comma-separated): " STAKEHOLDERS
STAKEHOLDERS="${STAKEHOLDERS:-N/A}"

echo ""
echo "  RAG priming levels:"
echo "    1) Minimal — Frontmatter only"
echo "    2) Standard — Full SKILL.md"
echo "    3) Deep — SKILL.md + references + examples"
echo ""
read -rp "  Select priming level [1-3, default 2]: " PRIME_NUM
case "${PRIME_NUM:-2}" in
  1) PRIMING_LEVEL="L1" ;;
  2) PRIMING_LEVEL="L2" ;;
  3) PRIMING_LEVEL="L3" ;;
  *) PRIMING_LEVEL="L2" ;;
esac

# ─── Step 2: Create project/ structure ───
echo ""
echo "--- Step 2/6: Creating project/ structure ---"

PROJECT_DIR="$TARGET_DIR/project"
mkdir -p "$PROJECT_DIR"/{deliverables,insights,transcripts,rag-priming,assets,attachments}

# Create .gitignore for sensitive files
cat > "$PROJECT_DIR/.gitignore" << 'GIEOF'
# APEX session files (sensitive, ephemeral)
apex-secrets-audit.log
apex-secrets-map.json
session-state.json
GIEOF

echo "  project/ structure created (7 subdirs)"

# ─── Step 3: Pre-populate SESSION-README.md ───
echo ""
echo "--- Step 3/6: Generating session context ---"

cat > "$PROJECT_DIR/SESSION-README.md" << SEOF
# Session Context — ${PROJECT_NAME}

> Generated by \`pm-init.sh\` — $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Project Information

| Field | Value |
|-------|-------|
| **Project** | ${PROJECT_NAME} |
| **Project Type** | ${TIPO_PROYECTO} |
| **Pipeline Mode** | ${PIPELINE_MODE} |
| **Repository** | ${REPO_PATH} |
| **Stakeholders** | ${STAKEHOLDERS} |
| **Priming Level** | ${PRIMING_LEVEL} |
| **Working Directory** | ${TARGET_DIR} |
| **Initialized by** | pm-init.sh v1.0 |

## Project Status

- **Current phase**: Pre-initiation (pending \`/pm:${PIPELINE_MODE}\`)
- **Deliverables**: 0/15
- **Gates passed**: 0/4

## Quick Start

\`\`\`bash
/pm:run-auto          # Full autonomous pipeline
/pm:run-guided        # Guided pipeline with human facilitation
/pm:run-express       # Quick Go/No-Go
/pm:run-deep          # Deep analysis pipeline
\`\`\`
SEOF

echo "  SESSION-README.md generated"

# Generate session-state.json
cat > "$PROJECT_DIR/session-state.json" << STEOF
{
  "session_start": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "plugin_version": "1.0.0",
  "initialized_by": "pm-init",
  "project_name": "${PROJECT_NAME}",
  "tipo_proyecto": "${TIPO_PROYECTO}",
  "pipeline_mode": "${PIPELINE_MODE}",
  "stakeholders": "${STAKEHOLDERS}",
  "priming_level": "${PRIMING_LEVEL}",
  "working_directory": "${TARGET_DIR}",
  "phase": "pre-initiation",
  "deliverables_count": 0,
  "gates_passed": 0,
  "g0_status": "pending"
}
STEOF

echo "  session-state.json generated"

# ─── Step 4: Auto-discovery ───
echo ""
echo "--- Step 4/6: Auto-discovery ---"

# Run repo indexer if available
if [ -f "$PLUGIN_DIR/scripts/index-repo.sh" ]; then
  echo "  Indexing repository..."
  bash "$PLUGIN_DIR/scripts/index-repo.sh" "$TARGET_DIR" 2>/dev/null || echo "  Repo indexing skipped (not a git repo or no files)"
else
  echo "  index-repo.sh not found, skipping auto-discovery"
fi

# ─── Step 5: G0 Security Scan ───
echo ""
echo "--- Step 5/6: G0 Security Gate ---"

G0_STATUS="CLEAN"
if [ -f "$PLUGIN_DIR/scripts/secrets-scan.sh" ]; then
  echo "  Running G0 security scan..."
  if bash "$PLUGIN_DIR/scripts/secrets-scan.sh" "$TARGET_DIR" 2>/dev/null; then
    echo "  G0 Security Gate: PASSED"
  else
    G0_STATUS="FINDINGS"
    echo "  G0 Security Gate: FINDINGS DETECTED"
    echo "     Review: project/apex-secrets-audit.log"
  fi
else
  echo "  secrets-scan.sh not found, skipping G0 gate"
fi

# Update session state with G0 result
if command -v jq &>/dev/null && [ -f "$PROJECT_DIR/session-state.json" ]; then
  TMP=$(mktemp)
  jq --arg status "$G0_STATUS" '.g0_status = $status' "$PROJECT_DIR/session-state.json" > "$TMP" && mv "$TMP" "$PROJECT_DIR/session-state.json"
fi

# ─── Step 6: Summary ───
echo ""
echo "--- Step 6/6: Summary ---"
echo ""
echo "  PMO-APEX initialized for ${PROJECT_NAME}"
echo ""
echo "  Configuration:"
echo "     Project:      ${PROJECT_NAME}"
echo "     Type:         ${TIPO_PROYECTO}"
echo "     Pipeline:     ${PIPELINE_MODE}"
echo "     Priming:      ${PRIMING_LEVEL}"
echo "     G0 Security:  ${G0_STATUS}"
echo ""
echo "  project/ structure:"

# Print tree if available
if command -v tree >/dev/null 2>&1; then
  tree -L 1 "$PROJECT_DIR" 2>/dev/null || ls "$PROJECT_DIR"
else
  ls "$PROJECT_DIR"
fi

echo ""
echo "  Next steps:"
if [ "$G0_STATUS" = "FINDINGS" ]; then
  echo "     1. Review secrets: /pm:scan-secrets"
  echo "     2. Then start project: /pm:${PIPELINE_MODE}"
else
  echo "     Start project: /pm:${PIPELINE_MODE}"
fi
echo ""
echo "  ================================================"

exit 0
