#!/usr/bin/env bash
# session-context-gen.sh — Session Context Generator
# PMO-APEX v1.0 — Agentic Project Management as Service
# © 2026 PMO-APEX. All Rights Reserved.
#
# Hook: SessionStart
# Generates SESSION-README.md and SESSION-CLAUDE.md in project/
# for the orchestrator to operate at full capacity with repos.

set -euo pipefail

TARGET_DIR="${1:-.}"
PROJECT_DIR="${TARGET_DIR}/project"
SESSION_README="${PROJECT_DIR}/SESSION-README.md"
SESSION_CLAUDE="${PROJECT_DIR}/SESSION-CLAUDE.md"

mkdir -p "${PROJECT_DIR}"

# Detect project context
PROJECT_NAME=$(basename "$(cd "$TARGET_DIR" && pwd)")
HAS_GIT=false
[[ -d "${TARGET_DIR}/.git" ]] && HAS_GIT=true

# Get repo stats
FILE_COUNT=0
SOURCE_COUNT=0
if ${HAS_GIT}; then
  FILE_COUNT=$(cd "$TARGET_DIR" && git ls-files 2>/dev/null | wc -l | tr -d ' ' || echo 0)
  SOURCE_COUNT=$(cd "$TARGET_DIR" && git ls-files 2>/dev/null | grep -cE '\.(ts|js|tsx|jsx|java|kt|py|go|rs|cs|rb|php|swift|dart)$' || echo 0)
fi

# Detect PM tool configurations
PM_TOOLS=""
[[ -f "${TARGET_DIR}/.jira.yml" || -f "${TARGET_DIR}/jira.config" ]] && PM_TOOLS="${PM_TOOLS}Jira, "
[[ -f "${TARGET_DIR}/azure-boards.yml" || -f "${TARGET_DIR}/.ado-config" ]] && PM_TOOLS="${PM_TOOLS}Azure DevOps, "
[[ -f "${TARGET_DIR}/.monday.yml" ]] && PM_TOOLS="${PM_TOOLS}Monday.com, "
[[ -f "${TARGET_DIR}/.asana.yml" ]] && PM_TOOLS="${PM_TOOLS}Asana, "
[[ -f "${TARGET_DIR}/sprint-backlog.md" || -f "${TARGET_DIR}/product-backlog.md" ]] && PM_TOOLS="${PM_TOOLS}Agile/Scrum, "
[[ -f "${TARGET_DIR}/kanban-board.md" || -f "${TARGET_DIR}/.kanban.yml" ]] && PM_TOOLS="${PM_TOOLS}Kanban, "
PM_TOOLS=$(echo "$PM_TOOLS" | sed 's/, $//')
[[ -z "$PM_TOOLS" ]] && PM_TOOLS="none detected"

# Detect primary language
PRIMARY_LANG="N/A (PM project)"
if [[ -f "${TARGET_DIR}/package.json" ]]; then PRIMARY_LANG="JavaScript/TypeScript"
elif [[ -f "${TARGET_DIR}/pom.xml" ]] || [[ -f "${TARGET_DIR}/build.gradle" ]]; then PRIMARY_LANG="Java"
elif [[ -f "${TARGET_DIR}/Cargo.toml" ]]; then PRIMARY_LANG="Rust"
elif [[ -f "${TARGET_DIR}/go.mod" ]]; then PRIMARY_LANG="Go"
elif [[ -f "${TARGET_DIR}/pyproject.toml" ]] || [[ -f "${TARGET_DIR}/requirements.txt" ]]; then PRIMARY_LANG="Python"
elif compgen -G "${TARGET_DIR}/*.sln" > /dev/null 2>&1; then PRIMARY_LANG="C#/.NET"
fi

# Check for existing deliverables
DELIVERABLE_COUNT=0
DELIVERABLES_FOUND=""
for dir in "${TARGET_DIR}" "${PROJECT_DIR}/deliverables" "${TARGET_DIR}/output" "${TARGET_DIR}/outputs"; do
  if [[ -d "$dir" ]]; then
    while IFS= read -r f; do
      [[ -n "$f" ]] && DELIVERABLES_FOUND="${DELIVERABLES_FOUND}\n- $(basename "$f")"
      DELIVERABLE_COUNT=$((DELIVERABLE_COUNT + 1))
    done < <(find "$dir" -maxdepth 2 -name "*_*.md" -type f 2>/dev/null | grep -E '^.*[0-9]{2}[b]?_' || true)
  fi
done

# Check for priming-RAG files
RAG_COUNT=0
if [[ -d "${PROJECT_DIR}/rag-priming" ]]; then
  RAG_COUNT=$(find "${PROJECT_DIR}/rag-priming" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
fi

# Generate SESSION-README.md
cat > "$SESSION_README" << READMEEOF
# ${PROJECT_NAME} — PMO-APEX Project Session
> Auto-generated by PMO-APEX v1.0 | $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Project Context
| Attribute | Value |
|-----------|-------|
| Project | \`${PROJECT_NAME}\` |
| Language | ${PRIMARY_LANG} |
| PM Tools | ${PM_TOOLS} |
| Files | ${FILE_COUNT} total, ${SOURCE_COUNT} source |
| Git | $(${HAS_GIT} && echo "active" || echo "not detected") |
| Deliverables | ${DELIVERABLE_COUNT}/15 |
| RAG priming | ${RAG_COUNT} files |

## Pipeline Status
$(if [[ $DELIVERABLE_COUNT -eq 0 ]]; then
  echo "**Fresh start** — No deliverables found."
  echo ""
  echo "### Recommended next steps"
  echo "1. \`/pm:run-auto\` — Full autonomous pipeline"
  echo "2. \`/pm:run-express\` — Quick Go/No-Go (3 deliverables)"
  echo "3. \`/pm:run-guided\` — Guided pipeline with human facilitation"
elif [[ $DELIVERABLE_COUNT -lt 15 ]]; then
  echo "**In progress** — ${DELIVERABLE_COUNT}/15 deliverables completed."
  echo ""
  echo "### Deliverables found"
  echo -e "${DELIVERABLES_FOUND}"
  echo ""
  echo "### Recommended next steps"
  echo "1. \`/pm:rescue-stalled\` — Diagnose and complete"
  echo "2. \`/pm:audit-quality\` — Audit existing deliverables"
  echo "3. \`/pm:improve-deliverables\` — Evolve deliverables"
else
  echo "**Pipeline complete** — 15/15 deliverables."
  echo ""
  echo "### Recommended next steps"
  echo "1. \`/pm:audit-quality\` — Audit with scorecard"
  echo "2. \`/pm:improve-deliverables\` — Evolve deliverables"
fi)

## Session Files
| File | Path | Status |
|------|------|--------|
| Session README | \`project/SESSION-README.md\` | Done |
| Session CLAUDE | \`project/SESSION-CLAUDE.md\` | Done |
| Repo Index | \`project/repo-index.json\` | $([[ -f "${PROJECT_DIR}/repo-index.json" ]] && echo "Done" || echo "pending") |
| Changelog | \`project/session-changelog.md\` | $([[ -f "${PROJECT_DIR}/session-changelog.md" ]] && echo "Done" || echo "pending") |
| Ghost Menu | \`project/ghost-menu.md\` | $([[ -f "${PROJECT_DIR}/ghost-menu.md" ]] && echo "Done" || echo "pending") |

---
*PMO-APEX v1.0 — session context auto-generated.*
READMEEOF

# Generate SESSION-CLAUDE.md
cat > "$SESSION_CLAUDE" << CLAUDEEOF
# PMO-APEX — Session Instructions for the Orchestrator

> This file is auto-generated at the start of each session.
> It supplements the main CLAUDE.md with repo-specific context.
> The project-conductor must read this file to operate at full capacity.

## Active Repo Context
- **Project**: \`${PROJECT_NAME}\`
- **Primary language**: ${PRIMARY_LANG}
- **PM Tools**: ${PM_TOOLS}
- **Source files**: ${SOURCE_COUNT}
- **Existing deliverables**: ${DELIVERABLE_COUNT}/15
- **RAG priming available**: ${RAG_COUNT} files

## Session Rules

### Ghost Menu
Active on every response producing an important artifact.
Include contextual navigation block at the end with:
- Current phase status
- Deliverables completed vs pending
- Next recommended action
- Links to relevant session files

### Automatic Changelog
Every significant action is logged in \`project/session-changelog.md\`.
If session is interrupted, use changelog to resume.
On context crisis: read changelog first, then ghost menu.

### RAG Preparation
Each new attachment must be processed automatically:
1. Read/interpret
2. Create Markdown extract in \`project/rag-priming/\`
3. Update index
4. Incorporate into PM pipeline

### Orchestrator Operation
The project-conductor operates as permanent committee leader:
- Detects project type automatically
- Sequences phases respecting dependencies
- Applies quality gates (G1, G1.5, G2, G3)
- Manages cross-deliverable consistency
- Maintains evidence traceability with tags: [PLAN], [SCHEDULE], [METRIC], [DECISION]

### Session Priorities
$(if [[ $DELIVERABLE_COUNT -eq 0 ]]; then
  echo "1. Index the repo (CP-0)"
  echo "2. Detect project type"
  echo "3. Generate 00_Project_Charter"
  echo "4. Begin pipeline per selected mode"
elif [[ $DELIVERABLE_COUNT -lt 15 ]]; then
  echo "1. Diagnose current pipeline state"
  echo "2. Identify missing deliverables on critical path"
  echo "3. Complete or rescue pipeline"
  echo "4. Audit cross-deliverable consistency"
else
  echo "1. Audit deliverable quality"
  echo "2. Apply excellence loop"
  echo "3. Improve depth and evidence"
  echo "4. Generate additional outputs if requested"
fi)

---
*Generated by session-context-gen.sh | PMO-APEX v1.0 | $(date -u +%Y-%m-%dT%H:%M:%SZ)*
CLAUDEEOF

echo "Session context generated:"
echo "  ${SESSION_README}"
echo "  ${SESSION_CLAUDE}"
echo "  ${PROJECT_NAME} | ${PM_TOOLS} | ${FILE_COUNT} files | ${DELIVERABLE_COUNT}/15 deliverables"

exit 0
