#!/usr/bin/env bash
# Sovereign Architect — Post-Prime Calibration
# Recalibrates session state after priming or new artifact ingestion
# © 2026 JM Labs · Javier Montaño
set -euo pipefail

SA_DIR="${1:-$(pwd)}/sa"
DIGEST="$SA_DIR/calibration-digest.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [[ ! -d "$SA_DIR" ]]; then
  exit 0
fi

# Only recalibrate if priming marker was cleared or new RAG docs exist
if [[ -f "$SA_DIR/needs-priming" ]]; then
  RAG_COUNT=$(ls "$SA_DIR"/priming-rag-*.md 2>/dev/null | wc -l | tr -d ' ')
  if (( RAG_COUNT > 0 )); then
    rm -f "$SA_DIR/needs-priming"
    echo "- Priming marker cleared ($RAG_COUNT RAG docs found)."
  else
    exit 0
  fi
fi

# Generate/update calibration digest
ARTIFACT_COUNT=$(find "$SA_DIR" -name "*.md" -not -name ".*" 2>/dev/null | wc -l | tr -d ' ')
RAG_COUNT=$(ls "$SA_DIR"/priming-rag-*.md 2>/dev/null | wc -l | tr -d ' ')

cat > "$DIGEST" << EOF
# Calibration Digest
> Auto-generated by Sovereign Architect at $TIMESTAMP

| Metric | Value |
|--------|-------|
| RAG documents | $RAG_COUNT |
| Total artifacts | $ARTIFACT_COUNT |
| Last calibration | $TIMESTAMP |
| Status | Calibrated |

> Next recalibration triggers on new priming or significant artifact change.
EOF

echo "- Session recalibrated: $RAG_COUNT RAG docs, $ARTIFACT_COUNT artifacts."

exit 0
