#!/usr/bin/env bash
# Plugin QA — Session Context Generator
# Generates pqa/ session context files for the current project
# Hook: SessionStart
# (c) 2026 JM Labs - Javier Montano
set -euo pipefail

TARGET_DIR="${1:-$(pwd)}"
PQA_DIR="$TARGET_DIR/pqa"

mkdir -p "$PQA_DIR"

# Detect plugin
PLUGIN_NAME="none"
PLUGIN_VERSION="unknown"
PLUGIN_PATH=""
for manifest in "$TARGET_DIR/.claude-plugin/plugin.json" "$TARGET_DIR/plugin.json"; do
  if [[ -f "$manifest" ]]; then
    PLUGIN_NAME=$(grep -o '"name":\s*"[^"]*"' "$manifest" 2>/dev/null | head -1 | sed 's/"name":[[:space:]]*"//;s/"//' || echo "unknown")
    PLUGIN_VERSION=$(grep -o '"version":\s*"[^"]*"' "$manifest" 2>/dev/null | head -1 | sed 's/"version":[[:space:]]*"//;s/"//' || echo "unknown")
    PLUGIN_PATH="$manifest"
    break
  fi
done

# Count components
SKILLS=0; AGENTS=0; COMMANDS=0
[[ -d "$TARGET_DIR/skills" ]] && SKILLS=$(find "$TARGET_DIR/skills" -name "SKILL.md" -type f 2>/dev/null | wc -l | tr -d ' ')
[[ -d "$TARGET_DIR/agents" ]] && AGENTS=$(find "$TARGET_DIR/agents" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
[[ -d "$TARGET_DIR/commands" ]] && COMMANDS=$(find "$TARGET_DIR/commands" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')

# Git context
BRANCH="unknown"
LAST_COMMIT="unknown"
if [[ -d "$TARGET_DIR/.git" ]]; then
  BRANCH=$(git -C "$TARGET_DIR" branch --show-current 2>/dev/null || echo "unknown")
  LAST_COMMIT=$(git -C "$TARGET_DIR" log -1 --format="%h %s (%ar)" 2>/dev/null || echo "unknown")
fi

# Generate SESSION-README.md
cat > "$PQA_DIR/SESSION-README.md" <<EOF
# PQA Session Context — $PLUGIN_NAME

> Auto-generated by Plugin QA session-context-gen.sh
> Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')

## Target Plugin

- **Name**: $PLUGIN_NAME
- **Version**: $PLUGIN_VERSION
- **Path**: $TARGET_DIR
- **Manifest**: $PLUGIN_PATH

## Component Counts

- **Skills**: $SKILLS
- **Agents**: $AGENTS
- **Commands**: $COMMANDS

## Git

- **Branch**: $BRANCH
- **Last commit**: $LAST_COMMIT

---
*PQA v3.0 — The plugin that audits plugins.*
EOF

# Generate SESSION-CLAUDE.md
cat > "$PQA_DIR/SESSION-CLAUDE.md" <<EOF
# PQA Session Instructions — $PLUGIN_NAME

> Context-specific instructions for this PQA session.

## Active Target

- Plugin: **$PLUGIN_NAME** v$PLUGIN_VERSION
- Components: $SKILLS skills, $AGENTS agents, $COMMANDS commands
- Working directory: \`$TARGET_DIR\`

## Session Rules

1. Evidence tags on every finding: \`[SPEC]\` \`[SCANNED]\` \`[INFERRED]\` \`[ASSUMED]\`
2. Respect quality gates (G1-G4 for upstream, none for QA-only)
3. Use \`/pqa:menu\` for available commands
4. Read before write — scan existing plugin first
EOF

# Generate calibration-digest.md
cat > "$PQA_DIR/calibration-digest.md" <<EOF
# PQA Calibration Digest

- **Target plugin**: $PLUGIN_NAME v$PLUGIN_VERSION
- **Components detected**: $SKILLS skills, $AGENTS agents, $COMMANDS commands
- **Session initialized**: $(date -u '+%Y-%m-%dT%H:%M:%SZ')
- **Plugin detected**: $([ "$PLUGIN_NAME" != "none" ] && echo "YES" || echo "NO")

> Run \`/pqa:validate\` for quick check or \`/pqa:audit\` for full QA.
EOF

echo "- Generated 3 session files in pqa/"

exit 0
