#!/usr/bin/env bash
# Sovereign Architect — Session Context Generator
# Generates sa/ session context files for the current project
# © 2026 JM Labs · Javier Montaño
set -euo pipefail

TARGET_DIR="${1:-$(pwd)}"
SA_DIR="$TARGET_DIR/sa"

echo "## SA Session Context Generator"
echo ""

# 1. Ensure sa/ directory exists
mkdir -p "$SA_DIR"

# 2. Detect project type from manifests
PROJECT_TYPE="unknown"
PROJECT_NAME=$(basename "$TARGET_DIR")
if [[ -f "$TARGET_DIR/package.json" ]]; then
  PROJECT_TYPE="node"
  PROJECT_NAME=$(grep -o '"name":\s*"[^"]*"' "$TARGET_DIR/package.json" 2>/dev/null | head -1 | sed 's/"name":\s*"//;s/"//' || echo "$PROJECT_NAME")
elif [[ -f "$TARGET_DIR/Cargo.toml" ]]; then
  PROJECT_TYPE="rust"
elif [[ -f "$TARGET_DIR/go.mod" ]]; then
  PROJECT_TYPE="go"
elif [[ -f "$TARGET_DIR/pyproject.toml" ]] || [[ -f "$TARGET_DIR/requirements.txt" ]]; then
  PROJECT_TYPE="python"
elif [[ -f "$TARGET_DIR/pom.xml" ]] || [[ -f "$TARGET_DIR/build.gradle" ]]; then
  PROJECT_TYPE="jvm"
fi

# 3. Extract git context
BRANCH="unknown"
LAST_COMMIT="unknown"
CONTRIBUTORS=""
if [[ -d "$TARGET_DIR/.git" ]]; then
  BRANCH=$(git -C "$TARGET_DIR" branch --show-current 2>/dev/null || echo "unknown")
  LAST_COMMIT=$(git -C "$TARGET_DIR" log -1 --format="%h %s (%ar)" 2>/dev/null || echo "unknown")
  CONTRIBUTORS=$(git -C "$TARGET_DIR" shortlog -sn --no-merges HEAD 2>/dev/null | head -5 | sed 's/^[[:space:]]*/- /' || echo "- unknown")
fi

# 4. Generate SESSION-README.md
cat > "$SA_DIR/SESSION-README.md" <<EOF
# Session Context — $PROJECT_NAME

> Auto-generated by Sovereign Architect session-context-gen.sh
> Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')

## Project

- **Name**: $PROJECT_NAME
- **Type**: $PROJECT_TYPE
- **Path**: $TARGET_DIR

## Git

- **Branch**: $BRANCH
- **Last commit**: $LAST_COMMIT

## Top Contributors

$CONTRIBUTORS

---
*SA v2.0 — Evidence over enthusiasm.*
EOF
echo "- Generated SESSION-README.md"

# 5. Generate SESSION-CLAUDE.md
cat > "$SA_DIR/SESSION-CLAUDE.md" <<EOF
# Session Instructions — $PROJECT_NAME

> Context-specific instructions for this SA session.

## Active Context

- Project type: **$PROJECT_TYPE**
- Branch: **$BRANCH**
- Working directory: \`$TARGET_DIR\`

## Session Rules

1. Read before write — scan existing code first
2. Evidence tags on every claim
3. Respect quality gates (G0 → G1 → G1.5 → G2)
4. Use \`/sa:menu\` for available commands
EOF
echo "- Generated SESSION-CLAUDE.md"

# 6. Generate calibration-digest.md
PRIMING_COUNT=$(find "$SA_DIR" -maxdepth 1 -name "priming-rag-*.md" 2>/dev/null | wc -l | tr -d ' ')
cat > "$SA_DIR/calibration-digest.md" <<EOF
# Calibration Digest

- **Priming documents loaded**: $PRIMING_COUNT
- **Project type detected**: $PROJECT_TYPE
- **Session initialized**: $(date -u '+%Y-%m-%dT%H:%M:%SZ')
- **Priming state**: $([ "$PRIMING_COUNT" -gt 0 ] && echo "PRIMED" || echo "NEEDS-PRIMING")

> Run \`/sa:prime\` to load repository knowledge if state is NEEDS-PRIMING.
EOF
echo "- Generated calibration-digest.md"

# 7. Generate ghost-menu.md
cat > "$SA_DIR/ghost-menu.md" <<EOF
# Ghost Menu — $PROJECT_NAME

| Action | Command |
|--------|---------|
| Full analysis | \`/sa:analyze\` |
| Diagnose only | \`/sa:diagnose\` |
| Architecture map | \`/sa:map-architecture\` |
| Security audit | \`/sa:audit-security\` |
| Generate ADR | \`/sa:generate-adr\` |
| Review artifact | \`/sa:review\` |
| Advance phase | \`/sa:next\` |
EOF
echo "- Generated ghost-menu.md"

# 8. Generate session-state.json
cat > "$SA_DIR/session-state.json" <<EOF
{
  "version": "2.0",
  "project": "$PROJECT_NAME",
  "projectType": "$PROJECT_TYPE",
  "branch": "$BRANCH",
  "phase": "G0",
  "gatesPassed": [],
  "artifacts": [],
  "primingState": "$([ "$PRIMING_COUNT" -gt 0 ] && echo "primed" || echo "needs-priming")",
  "createdAt": "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
}
EOF
echo "- Generated session-state.json"

echo ""
echo "> **5 session files generated** in $SA_DIR"

exit 0
